FROM ubuntu
RUN apt-get update -y && apt-get update -y
RUN apt-get -y install python3 pip
RUN pip3 install flask pandas requests elasticsearch flask_paginate
WORKDIR /home/flask
CMD ["./flask_start.sh"]